apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: decoding-sdk-server
  name: decoding-sdk-server
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8010
  selector:
    io.kompose.service: decoding-sdk-server
status:
  loadBalancer: {}
